---
- name: Install Gitea and MySQL
  hosts: all
  become: yes

  vars:
    gitea_version: "1.22.4"
    gitea_user: "git"
    gitea_group: "git"
    gitea_home: "/home/git"
    gitea_work_dir: "/var/lib/gitea"
    gitea_bin: "/usr/local/bin/gitea"
    gitea_service: "/etc/systemd/system/gitea.service"
    gitea_config: "/etc/gitea/app.ini"
    mysql_root_password: "password"
    gitea_db_name: "gitea"
    gitea_db_user: "giteadb"
    gitea_db_password: "password"

  tasks:
    - name: Create git group
      group:
        name: "{{ gitea_group }}"
        system: yes

    - name: Create git user
      user:
        name: "{{ gitea_user }}"
        group: "{{ gitea_group }}"
        system: yes
        shell: /bin/bash
        comment: "Git Version Control"
        home: "{{ gitea_home }}"
        create_home: yes

    - name: Create Gitea directories
      file:
        path: "{{ item }}"
        state: directory
        owner: "{{ gitea_user }}"
        group: "{{ gitea_group }}"
        mode: '0750'
      with_items:
        - "{{ gitea_work_dir }}/custom"
        - "{{ gitea_work_dir }}/data"
        - "{{ gitea_work_dir }}/log"

    - name: Create /etc/gitea directory
      file:
        path: /etc/gitea
        state: directory
        owner: root
        group: "{{ gitea_group }}"
        mode: '0770'

    - name: Create Gitea service file
      copy:
        dest: "{{ gitea_service }}"
        content: |
          [Unit]
          Description=Gitea (Git with a cup of tea)
          After=network.target

          [Service]
          RestartSec=2s
          Type=simple
          User={{ gitea_user }}
          Group={{ gitea_group }}
          WorkingDirectory={{ gitea_work_dir }}
          ExecStart={{ gitea_bin }} web --config {{ gitea_config }}
          Restart=always
          Environment=USER={{ gitea_user }} HOME={{ gitea_work_dir }} GITEA_WORK_DIR={{ gitea_work_dir }}

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Install libcap
      yum:
        name: libcap
        state: present

    - name: Set capabilities for Gitea binary
      command: setcap 'cap_net_bind_service=+ep' {{ gitea_bin }}

    - name: Install MySQL server and Python MySQL dependencies
      dnf:
        name:
          - mysql-server
          - mysql
          - python3
          - python3-PyMySQL
        state: present

    - name: Start and enable MySQL service
      systemd:
        name: mysqld
        enabled: yes
        state: started

    - name: Wait for MySQL to be ready
      wait_for:
        port: 3306
        timeout: 30

    - name: Set MySQL root password
      shell: |
        mysqladmin -u root password "{{ mysql_root_password }}"
      ignore_errors: yes

    - name: Create Gitea database
      shell: |
        mysql -u root -p"{{ mysql_root_password }}" -e "CREATE DATABASE IF NOT EXISTS {{ gitea_db_name }} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
      ignore_errors: no

    - name: Create Gitea database user and grant privileges
      shell: |
        mysql -u root -p"{{ mysql_root_password }}" -e "CREATE USER IF NOT EXISTS '{{ gitea_db_user }}'@'localhost' IDENTIFIED BY '{{ gitea_db_password }}';"
        mysql -u root -p"{{ mysql_root_password }}" -e "GRANT ALL PRIVILEGES ON {{ gitea_db_name }}.* TO '{{ gitea_db_user }}'@'localhost';"
        mysql -u root -p"{{ mysql_root_password }}" -e "FLUSH PRIVILEGES;"
      ignore_errors: no

    - name: Create Gitea configuration file
      template:
        dest: "{{ gitea_config }}"
        owner: "{{ gitea_user }}"
        group: "{{ gitea_group }}"
        mode: '0660'
        content: |
          [database]
          DB_TYPE  = mysql
          HOST     = 127.0.0.1:3306
          NAME     = {{ gitea_db_name }}
          USER     = {{ gitea_db_user }}
          PASSWD   = {{ gitea_db_password }}
          
          [server]
          DOMAIN           = localhost
          HTTP_PORT        = 3000
          ROOT_URL         = http://localhost:3000/
          
          [repository]
          ROOT = {{ gitea_work_dir }}/repositories
          
          [log]
          ROOT_PATH = {{ gitea_work_dir }}/log

    - name: Enable and start Gitea service
      systemd:
        name: gitea
        enabled: yes
        state: started

    - name: Wait for Gitea to be ready
      wait_for:
        port: 3000
        timeout: 30

    - name: Check Gitea service status
      command: systemctl status gitea
      register: gitea_status
      changed_when: false
      failed_when: gitea_status.rc != 0

    - name: Verify Gitea web interface is responding
      uri:
        url: http://localhost:3000/
        return_content: yes
        status_code: 200
      register: gitea_response
      retries: 3
      delay: 5
      until: gitea_response.status == 200

    - name: Check if SELinux is installed
      stat:
        path: /etc/selinux/config
      register: selinux_check

    - name: Configure SELinux for Gitea
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes
      when: 
        - selinux_check.stat.exists
        - ansible_selinux is defined
        - ansible_selinux.status == "enabled"
